name: Linting & code analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install

      - name: Check flake8 version
        run: |
          poetry run python3 --version
          poetry run flake8 --version
          poetry run python3 -m flake8 --version
          python -m poetry run flake8 --version
          python3 -m poetry run flake8 --version

      - name: Run linting analysis
        run: |
          poetry run flake8 src/
          poetry run mypy --namespace-packages src/
          poetry run pylint src/
          poetry run black --check src/
