name: Linting & code analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          poetry env use $PYTHON_VERSION
          poetry install

      - name: Run linting analysis
        run: |
          poetry run flake8 bottica/
          poetry run mypy --namespace-packages bottica/
          poetry run pylint bottica/
          poetry run black --check bottica/
