name: Linting & code analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-dev.txt
      - run: pip install -r requirements.txt

      - name: Analyse code with mypy
        run: mypy --namespace-packages src/
      - name: Analyse code with pylint
        run: pylint src/
      - name: Analyse code with flake8
        run: flake8 src/
      - name: Analyse code with black
        run: black --check src/
